### PR TITLE
Remove Custom Setup.hs

### PR DESCRIPTION
**Pull request by mpickering**
Cabal since version 1.20.0.0 has defined the __HADDOCK_VERSION__ macro which indicates when we are building haddock documentation.

This alleviates the need for a custom Setup.hs script.

### CODE REVIEW

**Comment by andreasabel** [comment]
@snoyberg : Would you be willing to move maintainership to me?
- Write access to this repo.
- Uploader rights on hackage.

**Comment by snoyberg** [comment]
Sounds great, what's your Hackage username?

**Comment by andreasabel** [comment]
I am AndreasAbel https://hackage.haskell.org/user/AndreasAbel

**Comment by snoyberg** [comment]
Added on Hackage and invite sent here on GitHub. Welcome aboard!

**Comment by andreasabel** [comment]
Excellent!  
My goal is to release this PR as 0.4.14.1.

**Comment by andreasabel** [comment]
Candidates:
- https://hackage.haskell.org/package/system-filepath-0.4.14.1/candidate
- https://hackage.haskell.org/package/system-fileio-0.3.16.5/candidate

**Comment by ddssff** [comment]
Oh wow sorry about your day.   But thanks!

**Pull request merged**
